name: windows_controller
description: A simple way to send device usage commands to Windows

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.6+0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

